[server]
headless = true
enableCORS = false
enableXsrfProtection = false
# give the websocket more time before the proxy decides it's dead
websocketPingTimeout = 120
# avoid re-executing on every file change in Render
runOnSave = false

[client]
toolbarMode = "viewer"

[theme]
base = "light"
