[theme]
base="light"
primaryColor="#0B1221"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F6F7FA"
textColor="#0B1221"
font="sans serif"

[server]
headless = true
enableCORS = false
maxUploadSize = 200
